### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by taomin597715379** [llgcode/ps#3]
I'm glad to see your project，but many ps files in the samples directory failed to pass the test. Do you have any plans to continue to improve this project?

**Comment by llgcode** [comment]
Hi Taomin,
I have no plan to work on these samples. You can contribute if you want

**Comment by taomin597715379** [comment]
ok, i got it

**Comment by taomin597715379** [comment]
I feel that the parsing of postscript syntax seems very difficult, I try my best to do it。

**Comment by llgcode** [comment]
Not so difficult to parse, what do you need?

**Comment by taomin597715379** [comment]
Analyze EPS or AI format images, then rasterize them, and finally use imageMagic to compress it.
